
version: '3.8'

services:
  db:
    image: arm64v8/mysql:latest
    environment:
      - MYSQL_DATABASE=tv
      - MYSQL_ROOT_PASSWORD=Artfarts7
      - MySQL_USER=root
      - MYSQL_PASSWORD=Artfarts7
    ports:
      - "3300:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: ["mysqld"]

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tv?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    volumes: [./target/java_web_final_project-0.0.1-SNAPSHOT.jar:/java_web.jar]
    entrypoint: ["java", "-jar", "java_web.jar"]